### ISSUE TITLE
Naima for python 3.6

### ISSUE THREAD

**Issue by rlopezcoto** [zblz/naima#141] opened 2017-04-24 15:19 UTC
@cdeil asked what was the problem with installing naima with python 3.6. This is the message I get when trying to install it with anaconda:

(py36) Rubens-MacBook-Pro:~ rlopezcoto$ conda install naima
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - naima -> emcee >=2.1.0 -> python 3.4* -> openssl 1.0.1*
  - naima -> emcee >=2.1.0 -> python 3.4* -> xz 5.0.5
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by cdeil** [comment] 2017-04-24 18:03
I think the problem is just that there's no conda package for Naima for Python 3.6 yet:
https://anaconda.org/astropy/naima/files

@rlopezcoto - You should be able to use Naima with Python 3.6 if you `pip install naima` (which will install the latest stable version from source from PyPI:
https://pypi.python.org/pypi/naima/0.8
For me this works fine with Python 3.6

@zblz - Does it make sense to do a new release for naima, to get new conda packages including for Python 3.6?

**Comment by rlopezcoto** [comment] 2017-04-24 19:06
Thanks @cdeil, it was installed as you suggested without any problems

**Comment by zblz** [comment] 2017-04-24 22:42
@rlopezcoto, @cdeil - thanks for spotting this. I looked into it and there are naima packages for Python 3.6, but the emcee dependency (which is also built in the astropy channel) does not have a 3.6 version yet, so it blocks the naima installation.

According to @bsipocz and @mwcraig in https://github.com/astropy/conda-channel-astropy/pull/132, the reason is that there is already a package on conda-forge and the current build pipeline for the astropy channel has some difficulties with it.

**Comment by zblz** [comment] 2017-04-24 22:54
While the fix is in progress in https://github.com/astropy/conda-channel-astropy/pull/146, `naima` can be installed through conda for python 3.6 by including the `conda-forge` channel in addition to the `astropy` channel:
```
conda install -c astropy -c conda-forge naima
```

**Comment by bsipocz** [comment] 2017-04-25 11:02
The build dates seems a bit weird on the conda channel, but now everything seems to be there, including emcee and corner. So

```
conda install -c astropy naima
```
 should work now. It it doesn't, please open an issue in  http://github.com/astropy/conda-channel-astropy

**Comment by zblz** [comment] 2017-04-25 19:05
Thanks @bsipocz!

**Closed by zblz** 2017-04-25 19:05 UTC
