### ISSUE TITLE
Don't use pickle

### ISSUE THREAD

**Issue by cdeil** [zblz/naima#73] opened 2015-03-12 17:27 UTC
I think `naima` shouldn't use `pickle` ... instead of giving reasons I'll just point to this talk:
https://www.youtube.com/watch?v=7KnfGDajDQw

CVS, FITS, JSON and YAML, even XML or HDF5 are all better options any time you store and possibly exchange data or results.

**Comment by zblz** [comment] 2015-03-12 17:30
I agree! 
Recovering the pickled sampler is a pain in the ass because you have to import the namespace. I've been thinking of saving only the chain and the spectral data, which are the important information of the sampler. I'll look into making a convenience function to save the chain.

**Comment by zblz** [comment] 2015-03-13 09:16
However, the issue that Aion found (which is issue #72), comes from the pickling done by multiprocessing within emcee. multiprocessing requires all functions and arguments passes to be serialized by pickle, resulting in some problems because of pickle's limitations. See, e.g., [this blog post](http://matthewrocklin.com/blog/work/2013/12/05/Parallelism-and-Serialization/)  for a description of the problem.

I will make a function to save the results, but the multiprocessing pickle is one we cannot avoid (without adding more dependencies).

**Comment by cdeil** [comment] 2015-03-13 09:29
Yes, Python multiprocessing is nice as long as it works (we started using it in Gammapy very recently [here](https://github.com/gammapy/gammapy/blob/88b22048a69ea5941cbf6647ab3464218edce66b/gammapy)), but when there's a pickle error you're either screwed or have to painfully change your code to make it work somehow.

In your case if this is baked into `emcee` I guess there's nothing you can do, or do they have alternative methods to use multi-core?
For `gammapy` I'm looking for a simple message-passing solution that doesn't use `pickle` ... I haven't tried much and don't know how the other options like `IPython.parallel` or `joblib` or ... work ... hopefully there's an easy-to-install and -use one that doesn't use `multiprocessing` under the hood.

**Comment by zblz** [comment] 2015-03-16 17:56
Yes, the constraint for `naima` is the use of multiprocessing in `emcee`, so there is nothing to do there. I opened an [issue with astropy QTable](https://github.com/astropy/astropy/issues/3590), so hopefully this will be solved upstream.

For `gammapy`, if you are OK with adding more dependencies, there is a multiprocessing clone that uses `dill` instead of `pickle` and apparently has better serialization. The multiprocessing clone is in the `pathos` library (see blog post above) but I haven't used it, so I don't know how well it would fit your needs.

**Comment by zblz** [comment] 2015-03-21 16:01
I solved the issue with QTable pickling upstream (see PR attached to issue above, hopefully will go into astropy 1.0.2). I still haven't thought a way of saving the sampler results without using pickle. The problem is that the models can return blobs that could be in any data format, and parsing them into, e.g., structured arrays, could be a lot of work. I could try to make an object without any namespace references and pickle that.

**Comment by cdeil** [comment] 2015-03-22 09:00
Looks like has implemented different backends (pickle, sqlite, hdf5) to store samples (see [here](http://pymc-devs.github.io/pymc/database.html) and emcee doesn't have that built in (although see [here](https://github.com/dfm/emcee/pull/60)).

I don't understand what exactly you want to store (the blobs returned by models), if it's just the trace of sampled parameters is should be easy to write and read to a table with not much code, no?

**Comment by zblz** [comment] 2015-03-23 11:25
The trace of the sampled parameters is trivial to store, indeed. The blobs are arbitrary things that the models can return on each execution and get saved if the parameter vector is accepted into the sample chain. This way you can sample secondary products of you model (e.g., total energy in particles above a certain energy, or save the full shape of the particle distribution). Arguably, many of these could be computed after the fact from the sampled parameters, but it is very convenient to save them at execution time.

Regarding the emcee PR you linked, I already do that in the examples. Essentially, the only thing it does is remove the multiprocessing pool from the sampler (which is stored in ``sampler.Pool``) because it cannot be pickled. It does not improve the situation with respect to the references to the namespace of the sampler (with the biggest offender being the log-probability funciton, which is referenced as ``sampler.lnprobfn``).

**Comment by cdeil** [comment] 2015-03-23 11:48
If the current solution using pickle works and implementing a different serialisation format is hard, maybe just close this issue and leave as is (and maybe add a warning to the docs that these files shouldn't be shared with different users and there's a good chance they won't work when using a different machine or python interpreter).

**Comment by zblz** [comment] 2015-08-03 15:32
The PR for astropy QTable pickling went into 1.0.2, so now naima requires this version. I don't see a short-term way of improving the saving of the sampler while including the functions, so I will close this issue and reconsider at a later date.

**Closed by zblz** 2015-08-03 15:32 UTC

**Comment by zblz** [comment] 2015-08-14 18:19
@cdeil: I ended up writing saving/retrieving methods for the samplers in #86, but currently all blobs are dropped. With a bit of logic they could be restructured into arrays and then brought back to a list of lists, so I might try that at some point. Now I have to change all examples, but it is definitely nicer than pickling.
