### ISSUE TITLE
Unable to guess table format 

### ISSUE THREAD

**Issue by ZiweiOu** [zblz/naima#165] opened 2018-01-28 13:45 UTC
Hi,
    When I run the example script 'RXJ1713_IC.py', it is fine. However, when I replace the data with my data, which is the results of data challenge 1 of Cherenkov Telescope Arrays, it shows the error:
**'ERROR: Unable to guess table format with the guesses listed below:'**
I am sure the format and structure of my data is the same as the original data 'RXJ1713_HESS_2007.dat' in the example script. So I don't understand where does my error come from. Hoping for suggestions.

**Comment by zblz** [comment] 2018-01-29 08:14
Hi,

In that example script, the data table is read in one of the first line with a call to `astropy.io.ascii.read`. Is is difficult to see what the problem is without seeing the file contents, but you might want to look at the [astropy docs](http://docs.astropy.org/en/latest/io/ascii/index.html) for more information about the `ascii` module that might solve your problem. Most likely there is a formatting error in the file.

I'll close this issue as it is not a problem in the code of `naima`.

**Closed by zblz** 2018-01-29 08:14 UTC
